"""
nodes/client_js_node.py — WebNode Framework

ClientJSNode: Writes frontend JavaScript code directly to /static/ directory.
Used from the Node Editor to author and deploy browser JS scripts
inline, without manually editing files.

Usage in main.py (auto-generated by compiler):
    clientjsnode = ClientJSNode('script.js', 'console.log("Hello");')
    clientjsnode.apply()  # writes /static/script.js at deploy time
"""
import os
import settings
from nodes.base_node import BaseNode

class ClientJSNode(BaseNode):
    """
    A standalone Client-side JavaScript node.

    - Stores JS code and a target filename.
    - On apply(), writes the JS to settings.STATIC_ROOT/<filename>.
    - Does NOT participate in the request/response chain (no in-port).
    """

    def __init__(self, filename: str, js_code: str = ''):
        super().__init__()
        self.filename = filename
        self.js_code = js_code

    def apply(self):
        """Write JS code to the static directory."""
        if not self.filename:
            return
        # Ensure filename ends with .js
        fname = self.filename if self.filename.endswith('.js') else self.filename + '.js'
        dest = os.path.join(settings.STATIC_ROOT, fname)
        os.makedirs(settings.STATIC_ROOT, exist_ok=True)
        with open(dest, 'w', encoding='utf-8') as f:
            f.write(self.js_code)
        print(f'[ClientJSNode] Written: {dest}')

    def process(self, request):
        """ClientJSNode doesn't process requests — it's a static asset node."""
        return super().process(request)

    def __repr__(self):
        return f'<ClientJSNode filename={self.filename!r}>'
