"""
nodes/css_node.py — WebNode Framework

CSSNode: Writes CSS code directly to /static/ directory.
Used from the Node Editor to author and deploy CSS stylesheets
inline, without manually editing files.

Usage in main.py (auto-generated by compiler):
    cssnode = CSSNode('shop.css', '''body { margin: 0; }''')
    cssnode.apply()  # writes /static/shop.css at deploy time
"""
import os
import settings
from nodes.base_node import BaseNode


class CSSNode(BaseNode):
    """
    A standalone CSS style node.

    - Stores CSS code and a target filename.
    - On apply(), writes the CSS to settings.STATIC_ROOT/<filename>.
    - Does NOT participate in the request/response chain (no in-port).
    - Can be chained to a RenderNode for auto-injection (future).
    """

    def __init__(self, filename: str, css_code: str = ''):
        super().__init__()
        self.filename = filename
        self.css_code = css_code

    def apply(self):
        """Write CSS code to the static directory."""
        if not self.filename:
            return
        # Ensure filename ends with .css
        fname = self.filename if self.filename.endswith('.css') else self.filename + '.css'
        dest = os.path.join(settings.STATIC_ROOT, fname)
        os.makedirs(settings.STATIC_ROOT, exist_ok=True)
        with open(dest, 'w', encoding='utf-8') as f:
            f.write(self.css_code)
        print(f'[CSSNode] Written: {dest}')

    def process(self, request):
        """CSSNode doesn't process requests — it's a static asset node."""
        return super().process(request)

    def __repr__(self):
        return f'<CSSNode filename={self.filename!r}>'