import http.server
import socketserver
import json
import os
import sys
import subprocess
import socket
import webbrowser
import threading
import urllib.parse
import urllib.request
import urllib.error
import ssl
try:
    ssl._create_default_https_context = ssl._create_unverified_context
except AttributeError:
    pass


# AI Settings Helper Functions
def load_ai_settings():
    config = {
        "SELECTED_AI_PROVIDER": "ollama",
        "GEMINI_API_KEY": "",
        "GEMINI_MODEL": "gemini-1.5-flash",
        "OPENAI_API_KEY": "",
        "OPENAI_MODEL": "gpt-4o-mini",
        "CLAUDE_API_KEY": "",
        "CLAUDE_MODEL": "claude-3-5-sonnet-20241022",
        "DEEPSEEK_API_KEY": "",
        "DEEPSEEK_MODEL": "deepseek-chat",
        "OPENROUTER_API_KEY": "",
        "OPENROUTER_MODEL": "google/gemini-2.0-flash-exp:free",
        "NVIDIA_API_KEY": "",
        "NVIDIA_MODEL": "qwen/qwen3-coder-480b-a35b-instruct",
        "GLM_API_KEY": "",
        "GLM_MODEL": "glm-4-flash",
        "DOUGH_API_KEY": "",
        "DOUGH_MODEL": "deepseek-chat",
        "CUSTOM_API_KEY": "",
        "CUSTOM_MODEL": "custom-model",
        "CUSTOM_API_ENDPOINT": "",
        "OLLAMA_API_ENDPOINT": "http://localhost:11434/api/generate",
        "OLLAMA_MODEL": "gemma4:26b"
    }
    env_path = os.path.join(FRAMEWORK_DIR, '.env')
    if os.path.exists(env_path):
        try:
            with open(env_path, 'r', encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith('#'):
                        continue
                    if '=' in line:
                        k, _, v = line.partition('=')
                        k = k.strip()
                        v = v.strip()
                        if v.startswith(('"', "'")) and v.endswith(('"', "'")):
                            v = v[1:-1]
                        if k in config:
                            config[k] = v
        except Exception:
            pass
    return config

def save_ai_settings(config):
    env_path = os.path.join(FRAMEWORK_DIR, '.env')
    existing_lines = []
    if os.path.exists(env_path):
        try:
            with open(env_path, 'r', encoding='utf-8') as f:
                existing_lines = f.readlines()
        except Exception:
            pass
            
    # Normalize keys
    keys_to_update = {k: str(v) for k, v in config.items()}
    updated_lines = []
    
    for line in existing_lines:
        line_strip = line.strip()
        if line_strip and not line_strip.startswith('#') and '=' in line_strip:
            k, _, v = line_strip.partition('=')
            k_clean = k.strip()
            if k_clean in keys_to_update:
                line = f"{k_clean}={keys_to_update[k_clean]}\n"
                del keys_to_update[k_clean]
        updated_lines.append(line)
        
    for k, v in keys_to_update.items():
        if updated_lines and not updated_lines[-1].endswith('\n'):
            updated_lines[-1] += '\n'
        updated_lines.append(f"{k}={v}\n")
        
    try:
        with open(env_path, 'w', encoding='utf-8') as f:
            f.writelines(updated_lines)
    except Exception:
        pass

    # Ensure settings.py has the declarations
    settings_path = os.path.join(FRAMEWORK_DIR, 'settings.py')
    if os.path.exists(settings_path):
        try:
            with open(settings_path, 'r', encoding='utf-8') as f:
                settings_content = f.read()
                
            if "SELECTED_AI_PROVIDER" not in settings_content:
                decl_block = """
# ---------------------------------------------------------------------------
# AI Settings (Auto-generated by AI Editor Settings)
# ---------------------------------------------------------------------------
SELECTED_AI_PROVIDER = get_env('SELECTED_AI_PROVIDER', 'ollama')
GEMINI_API_KEY = get_env('GEMINI_API_KEY', '')
GEMINI_MODEL = get_env('GEMINI_MODEL', 'gemini-1.5-flash')
OPENAI_API_KEY = get_env('OPENAI_API_KEY', '')
OPENAI_MODEL = get_env('OPENAI_MODEL', 'gpt-4o-mini')
CLAUDE_API_KEY = get_env('CLAUDE_API_KEY', '')
CLAUDE_MODEL = get_env('CLAUDE_MODEL', 'claude-3-5-sonnet-20241022')
DEEPSEEK_API_KEY = get_env('DEEPSEEK_API_KEY', '')
DEEPSEEK_MODEL = get_env('DEEPSEEK_MODEL', 'deepseek-chat')
OPENROUTER_API_KEY = get_env('OPENROUTER_API_KEY', '')
OPENROUTER_MODEL = get_env('OPENROUTER_MODEL', 'google/gemini-2.0-flash-exp:free')
NVIDIA_API_KEY = get_env('NVIDIA_API_KEY', '')
NVIDIA_MODEL = get_env('NVIDIA_MODEL', 'qwen/qwen3-coder-480b-a35b-instruct')
GLM_API_KEY = get_env('GLM_API_KEY', '')
GLM_MODEL = get_env('GLM_MODEL', 'glm-4-flash')
DOUGH_API_KEY = get_env('DOUGH_API_KEY', '')
DOUGH_MODEL = get_env('DOUGH_MODEL', 'deepseek-chat')
CUSTOM_API_KEY = get_env('CUSTOM_API_KEY', '')
CUSTOM_MODEL = get_env('CUSTOM_MODEL', 'custom-model')
CUSTOM_API_ENDPOINT = get_env('CUSTOM_API_ENDPOINT', '')
OLLAMA_API_ENDPOINT = get_env('OLLAMA_API_ENDPOINT', 'http://localhost:11434/api/generate')
OLLAMA_MODEL = get_env('OLLAMA_MODEL', 'gemma4:26b')
"""
                with open(settings_path, 'a', encoding='utf-8') as f:
                    f.write(decl_block)
        except Exception:
            pass

# Port configuration
PORT = 8081
AI_EDITOR_DIR = os.path.dirname(os.path.abspath(__file__))
FRAMEWORK_DIR = os.path.dirname(AI_EDITOR_DIR)

# --- DUAL-AGENT & RAG HELPERS ---

def load_rag_content():
    rag_path = os.path.join(FRAMEWORK_DIR, 'core', 'ai', 'FRAMEWORK_RAG.md')
    ui_rag_path = os.path.join(FRAMEWORK_DIR, 'core', 'ai', 'UI_SKILL_RAG.md')
    content = ""
    if os.path.exists(rag_path):
        try:
            with open(rag_path, 'r', encoding='utf-8') as f:
                content += f.read() + "\n\n"
        except Exception:
            pass
    if os.path.exists(ui_rag_path):
        try:
            with open(ui_rag_path, 'r', encoding='utf-8') as f:
                content += f.read() + "\n\n"
        except Exception:
            pass
    return content

def get_graph_hash():
    graph_path = os.path.join(FRAMEWORK_DIR, 'node_editor', 'graph.json')
    if os.path.exists(graph_path):
        import hashlib
        try:
            with open(graph_path, 'rb') as f:
                return hashlib.md5(f.read()).hexdigest()
        except Exception:
            pass
    return ""

THINKER_SYSTEM_PROMPT = """You are a senior web architect planning a website.
Based on the user's idea, plan all the routes and features needed for a complete, functional website.

Identify if there are any ambiguities in the user's requirements (e.g. database schema specifications, layout styles, particular features).
If there are ambiguities, list them as clarifying questions. Keep them concise and relevant.
If no questions are needed, leave the clarifying_questions list empty.

Output ONLY a single JSON object with the following structure:
{
  "project_name": "Name of the project",
  "description": "Short description of the website",
  "design_system": "Describe visual design (e.g. dark cyberpunk with neon glows, Outfit font)",
  "clarifying_questions": [
     "question 1",
     "question 2"
  ],
  "routes": [
     {
       "path": "/",
       "name": "home",
       "purpose": "What this route does",
       "has_form": false,
       "data_needed": "Hardcoded or DB products list, etc."
     }
  ]
}
Do NOT wrap the output in markdown code blocks. Output ONLY raw JSON. Do NOT include any explanations outside the JSON."""

def get_coder_system_prompt():
    rag_content = load_rag_content()
    return f"""You are an AI Web Architecture Generator for our visual node-based web framework.
Your task is to implement the website design planned by the architect.

### FRAMEWORK REFERENCE DATABASE (RAG):
{rag_content}

### INSTRUCTIONS:
1. Generate the COMPLETE visual node graph (`graph.json`) representing the full application.
2. If there is an existing graph, update and edit it incrementally to add the requested pages, database nodes, logic code, HTML, CSS, or security nodes. Keep the unchanged parts of the graph intact where appropriate, but ensure all connections are correctly wired.
3. Every Python LogicNode code MUST return a dictionary with context variables, including 'csrf_token': `request.context.get('csrf_token', '')`.
4. Every HTML template in RenderNode MUST link to the CSSNode static filename: `<link rel="stylesheet" href="/static/FILENAME.css">`.
5. Every HTML form with `method="POST"` MUST contain a hidden csrf_token field: `<input type="hidden" name="csrf_token" value="{{{{ csrf_token }}}}}}">`.
6. Use SQLite database query handling through `ModelNode` or `sqlite3` inside `LogicNode` according to the RAG database.
7. Wrap your entire JSON response in a single ```json ... ``` block. Output ONLY the JSON block. Do not include any explanations outside the JSON block.

### NODE POSITIONING & LAYOUT RULES (CRITICAL):
- Every node in the graph MUST have neat coordinates (`x`, `y`) to lay out the graph in straight lines.
- Space consecutive nodes horizontally by exactly 250 pixels (representing a clean 5cm visual distance). For example: ServerNode at `x: 100`, HTTPRequestsNode at `x: 350`, URLNode at `x: 600`, LogicNode at `x: 850`, RenderNode at `x: 1100`, CSSNode at `x: 1350`.
- Keep the `y` coordinate constant (e.g. `y: 300`) for the main sequential pipeline to form a straight line.
- CRITICAL: DO NOT TRUNCATE CODE. Write complete functions, classes, and tags. Do NOT use placeholders like `...` or `/* rest of code */`. Ensure all output is complete.
- If there are multiple route URL branches, separate them vertically by changing the `y` coordinate (space parallel route flows vertically by 200 pixels. For example: Route 1 nodes aligned at `y: 150`, Route 2 nodes aligned at `y: 350`, Route 3 nodes aligned at `y: 550`).
- Ensure nodes do not cluster or overlap. Every node must be clearly visible and organized.
"""

def get_provider_request_details(provider, ai_config, api_key, system_prompt, user_prompt, stream=False, chat_history=None):
    url = ""
    headers = {
        "Content-Type": "application/json",
        "User-Agent": "NodeEditorFramework/1.0 Mozilla/5.0"
    }
    data = {}
    if chat_history is None:
        chat_history = []

    if provider == "ollama":
        url = ai_config.get("OLLAMA_API_ENDPOINT", "http://localhost:11434/api/generate")
        if not url:
            url = "http://localhost:11434/api/generate"
        if url.endswith("/"):
            url = url[:-1]
        if not url.endswith("/api/generate") and not url.endswith("/api/chat"):
            url = url + "/api/generate"
        
        # Compile chat history into prompt for Ollama
        history_str = ""
        for msg in chat_history:
            role = "User" if msg["role"] == "user" else "Assistant"
            history_str += f"{role}: {msg['content']}\n\n"

        data = {
            "model": ai_config.get("OLLAMA_MODEL", "gemma4:26b"),
            "prompt": f"{system_prompt}\n\n{history_str}User Prompt: {user_prompt}",
            "stream": stream,
            "options": {
                "num_ctx": 128000,
                "num_predict": 32000
            }
        }
    else:
        # Build standard messages list for chat completions
        messages = [{"role": "system", "content": system_prompt}]
        for msg in chat_history:
            messages.append({"role": msg["role"], "content": msg["content"]})
        messages.append({"role": "user", "content": user_prompt})

        if provider == "gemini":
            url = "https://generativelanguage.googleapis.com/v1beta/chat/completions"
            headers["Authorization"] = f"Bearer {api_key}"
            data = {
                "model": ai_config.get("GEMINI_MODEL", "gemini-1.5-flash"),
                "messages": messages,
                "stream": stream,
                "max_tokens": 32000
            }
        elif provider == "gpt":
            url = "https://api.openai.com/v1/chat/completions"
            headers["Authorization"] = f"Bearer {api_key}"
            data = {
                "model": ai_config.get("OPENAI_MODEL", "gpt-4o-mini"),
                "messages": messages,
                "stream": stream,
                "max_tokens": 16000
            }
        elif provider == "claude":
            url = "https://api.anthropic.com/v1/messages"
            headers = {
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
                "content-type": "application/json"
            }
            # Claude expects messages list WITHOUT system role (system is a top-level param)
            claude_messages = []
            for msg in chat_history:
                claude_messages.append({"role": msg["role"], "content": msg["content"]})
            claude_messages.append({"role": "user", "content": user_prompt})
            data = {
                "model": ai_config.get("CLAUDE_MODEL", "claude-3-5-sonnet-20241022"),
                "max_tokens": 8192,
                "system": system_prompt,
                "messages": claude_messages,
                "stream": stream
            }
        elif provider == "deepseek":
            url = "https://api.deepseek.com/v1/chat/completions"
            headers["Authorization"] = f"Bearer {api_key}"
            data = {
                "model": ai_config.get("DEEPSEEK_MODEL", "deepseek-chat"),
                "messages": messages,
                "stream": stream,
                "max_tokens": 8192
            }
        elif provider == "openrouter":
            url = "https://openrouter.ai/api/v1/chat/completions"
            headers["Authorization"] = f"Bearer {api_key}"
            headers["HTTP-Referer"] = "http://localhost:8081/"
            headers["X-Title"] = "Cybercore Matrix Builder"
            data = {
                "model": ai_config.get("OPENROUTER_MODEL", "google/gemini-2.0-flash-exp:free"),
                "messages": messages,
                "stream": stream,
                "max_tokens": 32000
            }
        elif provider == "nvidia":
            url = "https://integrate.api.nvidia.com/v1/chat/completions"
            headers["Authorization"] = f"Bearer {api_key}"
            data = {
                "model": ai_config.get("NVIDIA_MODEL", "qwen/qwen3-coder-480b-a35b-instruct"),
                "messages": messages,
                "stream": stream,
                "max_tokens": 32000
            }
        elif provider == "glm":
            url = "https://open.bigmodel.cn/api/paas/v4/chat/completions"
            headers["Authorization"] = f"Bearer {api_key}"
            data = {
                "model": ai_config.get("GLM_MODEL", "glm-4-flash"),
                "messages": messages,
                "stream": stream,
                "max_tokens": 32000
            }
        elif provider == "dough":
            url = "https://dough.id/api/v1/chat/completions"
            headers["Authorization"] = f"Bearer {api_key}"
            data = {
                "model": ai_config.get("DOUGH_MODEL", "deepseek-chat"),
                "messages": messages,
                "stream": stream,
                "max_tokens": 32000
            }
        elif provider == "custom":
            url = ai_config.get("CUSTOM_API_ENDPOINT", "")
            if api_key:
                headers["Authorization"] = f"Bearer {api_key}"
            data = {
                "model": ai_config.get("CUSTOM_MODEL", "custom-model"),
                "messages": messages,
                "stream": stream,
                "max_tokens": 32000
            }
    return url, headers, data

def call_llm_non_stream(provider, ai_config, api_key, system_prompt, user_prompt):
    url, headers, data = get_provider_request_details(provider, ai_config, api_key, system_prompt, user_prompt, stream=False)
    if not url:
        raise ValueError("API Endpoint URL not configured.")
    
    req = urllib.request.Request(
        url,
        data=json.dumps(data).encode('utf-8'),
        headers=headers
    )
    with urllib.request.urlopen(req, timeout=600) as response:
        resp_bytes = response.read()
        resp_json = json.loads(resp_bytes.decode('utf-8'))
        
        if provider == "ollama":
            return resp_json.get('response', '')
        elif provider == "claude":
            return resp_json.get('content', [{}])[0].get('text', '')
        else: # OpenAI compatible
            return resp_json.get('choices', [{}])[0].get('message', {}).get('content', '')

def extract_json_from_text(text):
    if not text:
        return None
    import re
    # Try ```json ... ``` blocks first
    match = re.search(r"```(?:json)?\s*([\{\[].*?[\}\]])\s*```", text, re.DOTALL)
    if match:
        raw = match.group(1)
    else:
        # Try finding raw { ... }
        s, e = text.find('{'), text.rfind('}')
        if s != -1 and e > s:
            raw = text[s:e+1]
        else:
            s, e = text.find('['), text.rfind(']')
            if s != -1 and e > s:
                raw = text[s:e+1]
            else:
                raw = text
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        # Try fixing common issues like trailing commas
        try:
            cleaned = re.sub(r',\s*([}\]])', r'\1', raw)
            return json.loads(cleaned)
        except json.JSONDecodeError:
            return None

# --- ORIGINAL CONFIGS AND SYSTEM PROMPT ---

SYSTEM_PROMPT = """You are an AI Web Architecture Generator for our visual node-based web framework.
Your task is to translate the user's website request into a directed node graph.

Your response must include a single, complete JSON configuration block representing the graph, wrapped in ```json ... ``` blocks.
Do NOT include any extra text inside the JSON code block.
Make sure all node IDs and connection mapping references match.

### IMPORTANT DESIGN RULES:
1. ALWAYS make the website visually stunning. Use curated CSS themes (vibrant gradients, neon shadows, glassmorphism, smooth animations) in CSSNode.
2. Avoid default browser styling. ALWAYS import and apply modern typography (like 'Outfit' or 'Orbitron' from Google Fonts) inside RenderNode HTML.
3. NEVER leave elements bare on the screen. ALWAYS wrap them in a centered container card (e.g. #game-container) with backdrop-filter: blur() and elegant border styling.
4. CSS LINK REQUIREMENT: You must link the CSSNode filename in the RenderNode HTML. Example: If css_filename is 'snake.css', write `<link rel='stylesheet' href='/static/snake.css'>` in the HTML <head>.
5. Avoid standard browser alert() boxes for events (like game-over). Instead, design modern, interactive on-screen HTML/CSS modal overlays (e.g. #game-over-overlay) that can be hidden/shown via JS classes.
6. Always implement interactive features using JSNode/LogicNode (e.g., interactive calculators, games, contact forms, or live dashboard stats).
7. Do not use placeholders. Provide fully working HTML, CSS, and JS/Python code.

### AVAILABLE NODES AND CONFIGURATIONS:

1. ServerNode
   - Represents the HTTP web server.
   - Config: { "ip": "127.0.0.1", "port": 8000 }
   - The graph must start with exactly one ServerNode.

2. HTTPRequestsNode
   - Parses low-level HTTP client sockets into RequestWrapper objects.
   - Config: {} (empty)
   - Must connect immediately after the ServerNode.

3. Security & Logging Nodes (Optional, place in-line between HTTPRequestsNode and URLNode):
   - ActionLoggerNode: Config: {} (Logs requests)
   - AntiBotNode: Config: {} (Blocks search scrapers/crawlers)
   - RateLimitNode: Config: {} (Limits request frequency)
   - CSRFNode: Config: {} (Validates CSRF tokens)
   - ScreenProtectionNode: Config: {} (Prevents screen scraping)

4. URLNode
   - Route path filter/segment matcher.
   - Config: { "path": "/some-path" }
   - Connects after the HTTPRequestsNode (or security nodes). Multiple URLNodes can branch out to handle multiple routes.

5. LogicNode (Python Logic Node)
   - Executes Python logic.
   - Config: { "code": "def process_logic(request):\\n    return { 'message': 'Hello' }" }
   - Must return a Python dictionary (which updates request.context).

6. JSNode (JavaScript Logic Node)
   - Executes JavaScript logic via Node.js under a subprocess.
   - Config: { "code": "function process_logic(request) {\\n    return { message: 'Hello' };\\n}" }
   - Must define `function process_logic(request)`. Returns a plain JavaScript object (updates request.context).

7. RenderNode
   - Renders HTML templates with string interpolation.
   - Config: { "filename": "index.html", "html_code": "..." }
   - Inside html_code, you can interpolate keys from request.context using `{key}`. ALWAYS reference the CSS file `/static/style.css` (or custom name) matching your CSSNode filename!

8. CSSNode
   - Applies styling dynamically.
   - Config: { "css_filename": "style.css", "css_code": "..." }
   - Must connect after a RenderNode.

### CONNECTION RULES:
- ServerNode -> HTTPRequestsNode
- HTTPRequestsNode -> [Optional Security Nodes] -> URLNode
- URLNode -> LogicNode or JSNode or RenderNode
- LogicNode or JSNode -> RenderNode
- RenderNode -> CSSNode

### MASTER EXAMPLE: NEON CYBERPUNK SNAKE GAME
Here is a complete JSON graph configuration representing a premium Neon Snake Game with on-screen modal layouts, glassmorphism, custom styling, and fully operational game loop. Notice the alignment of RenderNode template interpolation and CSSNode styling links:

```json
{
    "nodes": [
        {
            "id": "node-server",
            "type": "ServerNode",
            "x": 50,
            "y": 250,
            "config": {
                "ip": "127.0.0.1",
                "port": 8000
            }
        },
        {
            "id": "node-http",
            "type": "HTTPRequestsNode",
            "x": 250,
            "y": 250,
            "config": {}
        },
        {
            "id": "node-security",
            "type": "AntiBotNode",
            "x": 420,
            "y": 250,
            "config": {}
        },
        {
            "id": "node-url",
            "type": "URLNode",
            "x": 600,
            "y": 250,
            "config": {
                "path": "/"
            }
        },
        {
            "id": "node-logic",
            "type": "JSNode",
            "x": 800,
            "y": 250,
            "config": {
                "code": "function process_logic(request) {\\n    return {\\n        title: \\"NEON SNAKE: CYBER DECK\\",\\n        difficulty: \\"ELITE CYBERPUNK MODE\\",\\n        version: \\"v1.2.5\\"\\n    };\\n}"
            }
        },
        {
            "id": "node-render",
            "type": "RenderNode",
            "x": 1050,
            "y": 250,
            "config": {
                "filename": "snake_game.html",
                "html_code": "<!DOCTYPE html>\\n<html>\\n<head>\\n  <title>{title}</title>\\n  <link href='https://fonts.googleapis.com/css2?family=Outfit:wght@300;600;900&display=swap' rel='stylesheet'>\\n  <link rel='stylesheet' href='/static/snake.css'>\\n</head>\\n<body>\\n  <div id='game-container'>\\n    <h1>{title}</h1>\\n    <div id='scoreboard'>\\n      <div class='stat-card'>\\n        <span class='label'>SCORE</span>\\n        <span id='score' class='value'>000</span>\\n      </div>\\n      <div class='stat-card'>\\n        <span class='label'>HI-SCORE</span>\\n        <span id='high' class='value'>000</span>\\n      </div>\\n    </div>\\n    <div id='mode'>{difficulty}</div>\\n    <div class='canvas-wrapper'>\\n      <canvas id='snakeCanvas' width='400' height='400'></canvas>\\n      <div id='game-over-overlay' class='hidden'>\\n        <div class='overlay-content'>\\n          <h2 class='glitch'>DECK CRASHED</h2>\\n          <p>SYSTEM CRITICAL ERROR 0x7E</p>\\n          <button id='restart-btn' onclick='resetGame()'>REBOOT SYSTEM</button>\\n        </div>\\n      </div>\\n    </div>\\n    <div class='controls'>\\n      <button class='ctrl-btn up' onclick='moveUp()'>▲</button>\\n      <div class='ctrl-row'>\\n        <button class='ctrl-btn left' onclick='moveLeft()'>◀</button>\\n        <button class='ctrl-btn right' onclick='moveRight()'>▶</button>\\n      </div>\\n      <button class='ctrl-btn down' onclick='moveDown()'>▼</button>\\n    </div>\\n    <div class='footer'>SYSTEM VERSION: {version} | STATUS: ACTIVE</div>\\n  </div>\\n  <script>\\n    const canvas = document.getElementById('snakeCanvas');\\n    const ctx = canvas.getContext('2d');\\n    const scoreVal = document.getElementById('score');\\n    const highVal = document.getElementById('high');\\n    const overlay = document.getElementById('game-over-overlay');\\n    \\n    let score = 0;\\n    let highScore = localStorage.getItem('neonSnakeHighScore') || 0;\\n    highVal.innerText = String(highScore).padStart(3, '0');\\n\\n    let grid = 20;\\n    let count = 0;\\n    let isGameOver = false;\\n\\n    let snake = {\\n      x: 160,\\n      y: 160,\\n      dx: grid,\\n      dy: 0,\\n      cells: [{x: 160, y: 160}, {x: 140, y: 160}],\\n      maxCells: 2\\n    };\\n\\n    let apple = { x: 320, y: 320 };\\n\\n    function getRandomInt(min, max) {\\n      return Math.floor(Math.random() * (max - min)) + min;\\n    }\\n\\n    function loop() {\\n      if (isGameOver) return;\\n      requestAnimationFrame(loop);\\n      \\n      let speedLimit = 6;\\n      if (score >= 100) speedLimit = 4;\\n      if (score >= 200) speedLimit = 3;\\n\\n      if (++count < speedLimit) return;\\n      count = 0;\\n      \\n      ctx.clearRect(0, 0, canvas.width, canvas.height);\\n      \\n      ctx.strokeStyle = 'rgba(0, 255, 204, 0.03)';\\n      ctx.lineWidth = 1;\\n      for (let i = 0; i < canvas.width; i += grid) {\\n        ctx.beginPath();\\n        ctx.moveTo(i, 0);\\n        ctx.lineTo(i, canvas.height);\\n        ctx.stroke();\\n        ctx.beginPath();\\n        ctx.moveTo(0, i);\\n        ctx.lineTo(canvas.width, i);\\n        ctx.stroke();\\n      }\\n\\n      snake.x += snake.dx;\\n      snake.y += snake.dy;\\n\\n      if (snake.x < 0) snake.x = canvas.width - grid;\\n      else if (snake.x >= canvas.width) snake.x = 0;\\n\\n      if (snake.y < 0) snake.y = canvas.height - grid;\\n      else if (snake.y >= canvas.height) snake.y = 0;\\n\\n      snake.cells.unshift({x: snake.x, y: snake.y});\\n      if (snake.cells.length > snake.maxCells) {\\n        snake.cells.pop();\\n      }\\n\\n      ctx.fillStyle = '#ff0055';\\n      ctx.shadowBlur = 15;\\n      ctx.shadowColor = '#ff0055';\\n      \\n      ctx.beginPath();\\n      ctx.arc(apple.x + grid/2, apple.y + grid/2, grid/3, 0, Math.PI * 2);\\n      ctx.fill();\\n\\n      snake.cells.forEach(function(cell, index) {\\n        if (index === 0) {\\n          ctx.fillStyle = '#ffffff';\\n          ctx.shadowColor = '#ffffff';\\n          ctx.shadowBlur = 20;\\n        } else {\\n          ctx.fillStyle = '#00ffcc';\\n          ctx.shadowColor = '#00ffcc';\\n          ctx.shadowBlur = 10;\\n        }\\n        \\n        ctx.beginPath();\\n        ctx.roundRect(cell.x + 1, cell.y + 1, grid - 2, grid - 2, 4);\\n        ctx.fill();\\n\\n        if (cell.x === apple.x && cell.y === apple.y) {\\n          score += 10;\\n          scoreVal.innerText = String(score).padStart(3, '0');\\n          if (score > highScore) {\\n            highScore = score;\\n            localStorage.setItem('neonSnakeHighScore', highScore);\\n            highVal.innerText = String(highScore).padStart(3, '0');\\n          }\\n          snake.maxCells++;\\n          \\n          let validApple = false;\\n          while (!validApple) {\\n            apple.x = getRandomInt(0, 20) * grid;\\n            apple.y = getRandomInt(0, 20) * grid;\\n            validApple = true;\\n            for (let i = 0; i < snake.cells.length; i++) {\\n              if (snake.cells[i].x === apple.x && snake.cells[i].y === apple.y) {\\n                validApple = false;\\n                break;\\n              }\\n            }\\n          }\\n        }\\n\\n        for (let i = index + 1; i < snake.cells.length; i++) {\\n          if (cell.x === snake.cells[i].x && cell.y === snake.cells[i].y) {\\n            triggerGameOver();\\n          }\\n        }\\n      });\\n      ctx.shadowBlur = 0;\\n    }\\n\\n    function triggerGameOver() {\\n      isGameOver = true;\\n      overlay.classList.remove('hidden');\\n    }\\n\\n    function resetGame() {\\n      score = 0;\\n      scoreVal.innerText = '000';\\n      snake.x = 160;\\n      snake.y = 160;\\n      snake.cells = [{x: 160, y: 160}, {x: 140, y: 160}];\\n      snake.dx = grid;\\n      snake.dy = 0;\\n      snake.maxCells = 2;\\n      isGameOver = false;\\n      overlay.classList.add('hidden');\\n      requestAnimationFrame(loop);\\n    }\\n\\n    document.addEventListener('keydown', function(e) {\\n      if (e.which === 37 && snake.dx === 0) { snake.dx = -grid; snake.dy = 0; }\\n      else if (e.which === 38 && snake.dy === 0) { snake.dy = -grid; snake.dx = 0; }\\n      else if (e.which === 39 && snake.dx === 0) { snake.dx = grid; snake.dy = 0; }\\n      else if (e.which === 40 && snake.dy === 0) { snake.dy = grid; snake.dx = 0; }\\n    });\\n\\n    function moveUp() { if (snake.dy === 0) { snake.dy = -grid; snake.dx = 0; } }\\n    function moveDown() { if (snake.dy === 0) { snake.dy = grid; snake.dx = 0; } }\\n    function moveLeft() { if (snake.dx === 0) { snake.dx = -grid; snake.dy = 0; } }\\n    function moveRight() { if (snake.dx === 0) { snake.dx = grid; snake.dy = 0; } }\\n\\n    requestAnimationFrame(loop);\\n  </script>\\n</body>\\n</html>"
            }
        },
        {
            "id": "node-css",
            "type": "CSSNode",
            "x": 1320,
            "y": 250,
            "config": {
                "css_filename": "snake.css",
                "css_code": "body {\\n  background: radial-gradient(circle at center, #0c0f24 0%, #030408 100%);\\n  color: #00ffcc;\\n  font-family: 'Outfit', sans-serif;\\n  display: flex;\\n  justify-content: center;\\n  align-items: center;\\n  min-height: 100vh;\\n  margin: 0;\\n  overflow-x: hidden;\\n}\\n\\n#game-container {\\n  background: rgba(10, 12, 28, 0.75);\\n  backdrop-filter: blur(12px);\\n  -webkit-backdrop-filter: blur(12px);\\n  border: 1px solid rgba(0, 255, 204, 0.25);\\n  border-radius: 20px;\\n  padding: 30px;\\n  text-align: center;\\n  box-shadow: 0 0 50px rgba(0, 255, 204, 0.15), inset 0 0 20px rgba(0, 255, 204, 0.05);\\n  max-width: 440px;\\n  width: 90%;\\n  animation: fadeIn 0.8s ease-out;\\n}\\n\\n@keyframes fadeIn {\\n  from { opacity: 0; transform: translateY(20px); }\\n  to { opacity: 1; transform: translateY(0); }\\n}\\n\\nh1 {\\n  margin: 0 0 5px 0;\\n  font-size: 1.8rem;\\n  font-weight: 900;\\n  letter-spacing: 3px;\\n  text-transform: uppercase;\\n  background: linear-gradient(90deg, #00ffcc, #ff0055);\\n  -webkit-background-clip: text;\\n  -webkit-text-fill-color: transparent;\\n  text-shadow: 0 0 15px rgba(0, 255, 204, 0.3);\\n}\\n\\n#scoreboard {\\n  display: flex;\\n  justify-content: space-around;\\n  margin: 15px 0;\\n  gap: 15px;\\n}\\n\\n.stat-card {\\n  background: rgba(255, 255, 255, 0.03);\\n  border: 1px solid rgba(255, 255, 255, 0.05);\\n  border-radius: 10px;\\n  padding: 8px 20px;\\n  flex: 1;\\n}\\n\\n.stat-card .label {\\n  display: block;\\n  font-size: 0.7rem;\\n  color: #8f92a9;\\n  letter-spacing: 2px;\\n  text-transform: uppercase;\\n  margin-bottom: 2px;\\n}\\n\\n.stat-card .value {\\n  font-size: 1.4rem;\\n  font-weight: 700;\\n  color: #fff;\\n  font-family: monospace;\\n  text-shadow: 0 0 10px rgba(255, 255, 255, 0.5);\\n}\\n\\n#mode {\\n  color: #ff0055;\\n  font-size: 0.8rem;\\n  font-weight: 700;\\n  margin-bottom: 20px;\\n  letter-spacing: 2px;\\n  text-transform: uppercase;\\n  text-shadow: 0 0 8px rgba(255, 0, 85, 0.4);\\n}\\n\\n.canvas-wrapper {\\n  position: relative;\\n  width: 400px;\\n  height: 400px;\\n  margin: 0 auto;\\n  border-radius: 12px;\\n  overflow: hidden;\\n  box-shadow: 0 0 30px rgba(0, 0, 0, 0.6);\\n}\\n\\n#snakeCanvas {\\n  background: #05060f;\\n  border: 2px solid rgba(0, 255, 204, 0.2);\\n  border-radius: 12px;\\n  display: block;\\n}\\n\\n#game-over-overlay {\\n  position: absolute;\\n  top: 0;\\n  left: 0;\\n  width: 100%;\\n  height: 100%;\\n  background: rgba(5, 6, 15, 0.85);\\n  display: flex;\\n  justify-content: center;\\n  align-items: center;\\n  backdrop-filter: blur(8px);\\n  transition: opacity 0.3s ease;\\n}\\n\\n.hidden {\\n  display: none !important;\\n  opacity: 0;\\n  pointer-events: none;\\n}\\n\\n.overlay-content {\\n  text-align: center;\\n  animation: scaleUp 0.3s cubic-bezier(0.175, 0.885, 0.32, 1.275);\\n}\\n\\n@keyframes scaleUp {\\n  from { transform: scale(0.8); opacity: 0; }\\n  to { transform: scale(1); opacity: 1; }\\n}\\n\\n.overlay-content h2 {\\n  color: #ff0055;\\n  font-size: 2.2rem;\\n  font-weight: 900;\\n  margin: 0 0 5px 0;\\n  letter-spacing: 4px;\\n  text-shadow: 0 0 15px rgba(255, 0, 85, 0.6);\\n}\\n\\n.overlay-content p {\\n  color: #8f92a9;\\n  font-size: 0.85rem;\\n  letter-spacing: 1px;\\n  margin-bottom: 20px;\\n}\\n\\n#restart-btn {\\n  background: linear-gradient(135deg, #ff0055 0%, #a30036 100%);\\n  border: none;\\n  color: #fff;\\n  padding: 12px 28px;\\n  font-size: 0.9rem;\\n  font-weight: 700;\\n  border-radius: 30px;\\n  cursor: pointer;\\n  letter-spacing: 2px;\\n  box-shadow: 0 0 15px rgba(255, 0, 85, 0.4);\\n  transition: all 0.2s ease;\\n}\\n\\n#restart-btn:hover {\\n  transform: translateY(-2px);\\n  box-shadow: 0 0 25px rgba(255, 0, 85, 0.7);\\n}\\n\\n.controls {\\n  margin-top: 25px;\\n  display: flex;\\n  flex-direction: column;\\n  align-items: center;\\n  gap: 8px;\\n}\\n\\n.ctrl-row {\\n  display: flex;\\n  gap: 30px;\\n}\\n\\n.ctrl-btn {\\n  background: rgba(0, 255, 204, 0.05);\\n  border: 1px solid rgba(0, 255, 204, 0.3);\\n  color: #00ffcc;\\n  width: 50px;\\n  height: 40px;\\n  font-size: 1.1rem;\\n  border-radius: 8px;\\n  cursor: pointer;\\n  transition: all 0.2s ease;\\n  display: flex;\\n  justify-content: center;\\n  align-items: center;\\n}\\n\\n.ctrl-btn:hover {\\n  background: #00ffcc;\\n  color: #0c0f24;\\n  box-shadow: 0 0 15px #00ffcc;\\n}\\n\\n.ctrl-btn:active {\\n  transform: scale(0.95);\\n}\\n\\n.footer {\\n  margin-top: 25px;\\n  font-size: 0.7rem;\\n  color: #585a72;\\n  letter-spacing: 1px;\\n}"
            }
        }
    ],
    "connections": [
        {
            "source": "node-server",
            "target": "node-http"
        },
        {
            "source": "node-http",
            "target": "node-security"
        },
        {
            "source": "node-security",
            "target": "node-url"
        },
        {
            "source": "node-url",
            "target": "node-logic"
        },
        {
            "source": "node-logic",
            "target": "node-render"
        },
        {
            "source": "node-render",
            "target": "node-css"
        }
    ]
}
```
"""

# Global reference to running server process (for fallback mode)
active_process = None

def clean_history_text(text):
    import re
    # Remove markdown code blocks of json
    cleaned = re.sub(r'```json.*?```', '[Generated Graph JSON]', text, flags=re.DOTALL)
    return cleaned

class AIEditorHandler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=AI_EDITOR_DIR, **kwargs)

    def end_headers(self):
        # Disable caching to make development updates instantaneous
        self.send_header('Cache-Control', 'no-store, no-cache, must-revalidate, max-age=0')
        self.send_header('Pragma', 'no-cache')
        self.send_header('Expires', '0')
        super().end_headers()

    def do_GET(self):
        if self.path == '/api/status':
            self.handle_status()
            return
        elif self.path == '/api/errors':
            self.handle_errors()
            return
        elif self.path == '/api/load':
            self.handle_load()
            return
        elif self.path == '/api/settings/load':
            self.handle_load_settings()
            return
        
        if self.path.startswith('/node_editor/'):
            rel_path = self.path[len('/node_editor/'):]
            # Strip query parameters
            rel_path = rel_path.split('?')[0]
            file_path = os.path.join(FRAMEWORK_DIR, 'node_editor', rel_path)
            if os.path.exists(file_path):
                self.send_response(200)
                import mimetypes
                mime_type, _ = mimetypes.guess_type(file_path)
                if mime_type:
                    self.send_header('Content-Type', mime_type)
                self.end_headers()
                with open(file_path, 'rb') as f:
                    self.wfile.write(f.read())
                return
            else:
                self.send_error(404, "File not found inside node_editor")
                return
        super().do_GET()

    def do_POST(self):
        if self.path == '/api/chat/stream':
            self.handle_chat_stream()
        elif self.path == '/api/deploy':
            self.handle_deploy()
        elif self.path == '/api/stop':
            self.handle_stop()
        elif self.path == '/api/save':
            self.handle_save()
        elif self.path == '/api/clear-graph':
            self.handle_clear_graph()
        elif self.path == '/api/errors/clear':
            self.handle_clear_errors()
        elif self.path == '/api/settings/save':
            self.handle_save_settings()
        elif self.path == '/api/chat/clear':
            self.handle_clear_chat()
        else:
            self.send_error(404, "Endpoint not found")

    def handle_status(self):
        # 1. Try to query port 8080 backend first if it is running
        try:
            req = urllib.request.Request("http://localhost:8080/api/status", method="GET")
            with urllib.request.urlopen(req, timeout=1) as res:
                self.send_response(200)
                self.send_header('Content-Type', 'application/json')
                self.end_headers()
                self.wfile.write(res.read())
                return
        except Exception:
            pass

        # 2. Check local process status
        global active_process
        is_live = False
        if active_process and active_process.poll() is None:
            is_live = True

        graph_hash = get_graph_hash()

        self.send_response(200)
        self.send_header('Content-type', 'application/json')
        self.end_headers()
        self.wfile.write(json.dumps({
            'status': 'live' if is_live else 'offline',
            'graph_hash': graph_hash
        }).encode())


    def handle_errors(self):
        # 1. Try to query port 8080 backend first if it is running
        try:
            req = urllib.request.Request("http://localhost:8080/api/errors", method="GET")
            with urllib.request.urlopen(req, timeout=1) as res:
                self.send_response(200)
                self.send_header('Content-Type', 'application/json')
                self.end_headers()
                self.wfile.write(res.read())
                return
        except Exception:
            pass

        # 2. Check local error state json
        state_file = os.path.join(FRAMEWORK_DIR, 'core', 'logs', 'error_state.json')
        if os.path.exists(state_file):
            with open(state_file, 'r', encoding='utf-8') as f:
                state = json.load(f)
        else:
            state = {}

        self.send_response(200)
        self.send_header('Content-type', 'application/json')
        self.end_headers()
        self.wfile.write(json.dumps(state).encode())

    def handle_stop(self):
        # 1. Try to hit port 8080 stop endpoint if it is running
        try:
            req = urllib.request.Request("http://localhost:8080/api/stop", method="POST")
            with urllib.request.urlopen(req, timeout=1) as res:
                self.send_response(200)
                self.send_header('Content-Type', 'application/json')
                self.end_headers()
                self.wfile.write(res.read())
                return
        except Exception:
            pass

        # 2. Terminate local active process
        global active_process
        if active_process:
            active_process.terminate()
            active_process = None

        self.send_response(200)
        self.send_header('Content-type', 'application/json')
        self.end_headers()
        self.wfile.write(json.dumps({'status': 'stopped'}).encode())

    def handle_load(self):
        graph_path = os.path.join(FRAMEWORK_DIR, 'node_editor', 'graph.json')
        if os.path.exists(graph_path):
            with open(graph_path, 'r', encoding='utf-8') as f:
                graph_data = json.load(f)
        else:
            graph_data = {"nodes": [], "connections": []}
            
        self.send_response(200)
        self.send_header('Content-type', 'application/json')
        self.end_headers()
        self.wfile.write(json.dumps(graph_data).encode())

    def handle_save(self):
        content_length = int(self.headers['Content-Length'])
        post_data = self.rfile.read(content_length)
        graph_data = json.loads(post_data.decode('utf-8'))
        
        graph_path = os.path.join(FRAMEWORK_DIR, 'node_editor', 'graph.json')
        with open(graph_path, 'w', encoding='utf-8') as f:
            json.dump(graph_data, f, indent=4)
        
        self.send_response(200)
        self.send_header('Content-type', 'application/json')
        self.end_headers()
        self.wfile.write(json.dumps({'status': 'success'}).encode())

    def handle_clear_errors(self):
        state_file = os.path.join(FRAMEWORK_DIR, 'core', 'logs', 'error_state.json')
        try:
            if os.path.exists(state_file):
                os.remove(state_file)
        except Exception:
            pass
        self.send_response(200)
        self.send_header('Content-type', 'application/json')
        self.end_headers()
        self.wfile.write(json.dumps({'status': 'success'}).encode())

    def handle_load_settings(self):
        settings_data = load_ai_settings()
        self.send_response(200)
        self.send_header('Content-type', 'application/json')
        self.end_headers()
        self.wfile.write(json.dumps(settings_data).encode('utf-8'))

    def handle_save_settings(self):
        try:
            content_length = int(self.headers['Content-Length'])
            post_data = self.rfile.read(content_length)
            settings_data = json.loads(post_data.decode('utf-8'))
            
            save_ai_settings(settings_data)
            
            self.send_response(200)
            self.send_header('Content-type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({'status': 'success'}).encode('utf-8'))
        except Exception as e:
            self.send_response(500)
            self.send_header('Content-type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({'status': 'error', 'message': str(e)}).encode('utf-8'))
    def handle_clear_graph(self):
        try:
            graph_json_path = os.path.join(FRAMEWORK_DIR, 'node_editor', 'graph.json')
            empty_graph = {"nodes": [], "connections": []}
            with open(graph_json_path, 'w', encoding='utf-8') as f:
                json.dump(empty_graph, f, indent=4)
            
            # Delete chat history file on clear
            history_path = os.path.join(AI_EDITOR_DIR, 'chat_history.json')
            if os.path.exists(history_path):
                try:
                    os.remove(history_path)
                except Exception:
                    pass

            self.send_response(200)
            self.send_header('Content-type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({'status': 'success', 'message': 'Graph cleared successfully.'}).encode('utf-8'))
        except Exception as e:
            self.send_response(500)
            self.send_header('Content-type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({'status': 'error', 'message': str(e)}).encode('utf-8'))

    def handle_clear_chat(self):
        try:
            state_path = os.path.join(AI_EDITOR_DIR, 'session_state.json')
            history_path = os.path.join(AI_EDITOR_DIR, 'chat_history.json')
            for path in [state_path, history_path]:
                if os.path.exists(path):
                    try:
                        os.remove(path)
                    except Exception:
                        pass

            self.send_response(200)
            self.send_header('Content-type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({'status': 'success', 'message': 'Chat session cleared successfully.'}).encode('utf-8'))
        except Exception as e:
            self.send_response(500)
            self.send_header('Content-type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({'status': 'error', 'message': str(e)}).encode('utf-8'))

    def handle_chat_stream(self):
        content_length = int(self.headers['Content-Length'])
        post_data = self.rfile.read(content_length)
        payload = json.loads(post_data.decode('utf-8'))
        prompt = payload.get('prompt', '')
        graph = payload.get('graph', {"nodes": [], "connections": []})
        is_answer = payload.get('is_answer', False)

        ai_config = load_ai_settings()
        provider = ai_config.get("SELECTED_AI_PROVIDER", "ollama").lower()
        
        # Check API key presence (except for ollama)
        api_key = ""
        if provider == "gemini":
            api_key = ai_config.get("GEMINI_API_KEY")
        elif provider == "gpt":
            api_key = ai_config.get("OPENAI_API_KEY")
        elif provider == "claude":
            api_key = ai_config.get("CLAUDE_API_KEY")
        elif provider == "deepseek":
            api_key = ai_config.get("DEEPSEEK_API_KEY")
        elif provider == "openrouter":
            api_key = ai_config.get("OPENROUTER_API_KEY")
        elif provider == "nvidia":
            api_key = ai_config.get("NVIDIA_API_KEY")
        elif provider == "glm":
            api_key = ai_config.get("GLM_API_KEY")
        elif provider == "dough":
            api_key = ai_config.get("DOUGH_API_KEY")
        elif provider == "custom":
            api_key = ai_config.get("CUSTOM_API_KEY")
        if provider != "ollama" and not api_key:
            self.send_response(400)
            self.send_header('Content-Type', 'text/plain; charset=utf-8')
            self.end_headers()
            self.wfile.write(f"API Key for '{provider}' is missing. Please set it in the Settings menu (⚙️).".encode('utf-8'))
            return

        # Start streaming response immediately
        self.send_response(200)
        self.send_header('Content-Type', 'text/plain; charset=utf-8')
        self.send_header('Cache-Control', 'no-store')
        self.end_headers()

        state_path = os.path.join(AI_EDITOR_DIR, 'session_state.json')
        history_path = os.path.join(AI_EDITOR_DIR, 'chat_history.json')
        
        is_new_session = not graph or not graph.get('nodes') or len(graph.get('nodes', [])) <= 1
        
        if is_new_session:
            chat_history = []
            if os.path.exists(history_path):
                try:
                    os.remove(history_path)
                except Exception:
                    pass
        else:
            chat_history = []
            if os.path.exists(history_path):
                try:
                    with open(history_path, 'r', encoding='utf-8') as f:
                        chat_history = json.load(f)
                except Exception:
                    pass

        is_heal = "A runtime exception occurred" in prompt or "The deployment failed with this" in prompt
        
        # Determine Thinker Plan & Coder prompts
        original_prompt = prompt
        thinker_plan = None
        clarifying_questions = []
        current_graph = graph
        
        if is_heal:
            # Self-healing request: bypass thinker questions and go to Coder
            graph_path = os.path.join(FRAMEWORK_DIR, 'node_editor', 'graph.json')
            if os.path.exists(graph_path):
                try:
                    with open(graph_path, 'r', encoding='utf-8') as f:
                        current_graph = json.load(f)
                except Exception:
                    pass
            thinker_plan = {
                "project_name": "Self-Healing",
                "description": "Patches compile errors and runtime exceptions"
            }
            self.wfile.write("⚡ [Auto-Healing] Debugging visual graph and logic code...\n\n".encode('utf-8'))
            self.wfile.flush()
        elif is_answer:
            # Resuming with clarifying answers
            if os.path.exists(state_path):
                try:
                    with open(state_path, 'r', encoding='utf-8') as f:
                        state_data = json.load(f)
                        original_prompt = state_data.get('original_prompt', '')
                        thinker_plan = state_data.get('thinker_plan', {})
                        clarifying_questions = thinker_plan.get('clarifying_questions', [])
                        current_graph = state_data.get('graph', graph)
                except Exception:
                    pass
            
            if not thinker_plan:
                thinker_plan = {
                    "project_name": "Direct Generation",
                    "description": "Generating application from prompt"
                }
            self.wfile.write("⚡ Resuming generation with your answers...\n\n".encode('utf-8'))
            self.wfile.flush()
        else:
            # New user request: Run the Thinker Phase first, streaming it to the user
            self.wfile.write("🤔 AI Architect thinking and planning...\n\n".encode('utf-8'))
            self.wfile.flush()
            
            # Create a simplified copy of the graph for the thinker to avoid massive token prefill
            simplified_graph = {"nodes": [], "connections": current_graph.get("connections", [])}
            for node in current_graph.get("nodes", []):
                simple_node = {
                    "id": node.get("id"),
                    "type": node.get("type"),
                    "x": node.get("x"),
                    "y": node.get("y"),
                    "config": {}
                }
                config = node.get("config", {}) or {}
                if "path" in config:
                    simple_node["config"]["path"] = config["path"]
                if "filename" in config:
                    simple_node["config"]["filename"] = config["filename"]
                if "css_filename" in config:
                    simple_node["config"]["css_filename"] = config["css_filename"]
                if "query" in config:
                    simple_node["config"]["query"] = config["query"]
                simplified_graph["nodes"].append(simple_node)
            
            thinker_user_prompt = f"User Request: {prompt}\n\nCurrent Graph Structure:\n{json.dumps(simplified_graph, indent=2)}"
            
            thinker_raw = ""
            try:
                # Call Thinker model (stream)
                url_t, headers_t, data_t = get_provider_request_details(provider, ai_config, api_key, THINKER_SYSTEM_PROMPT, thinker_user_prompt, stream=True, chat_history=chat_history)
                req_t = urllib.request.Request(url_t, data=json.dumps(data_t).encode('utf-8'), headers=headers_t)
                
                with urllib.request.urlopen(req_t, timeout=300) as response_t:
                    buffer_t = b""
                    while True:
                        chunk_t = response_t.read(1024)
                        if not chunk_t:
                            break
                        buffer_t += chunk_t
                        while b"\n" in buffer_t:
                            line_bytes_t, buffer_t = buffer_t.split(b"\n", 1)
                            line_str_t = line_bytes_t.decode('utf-8').strip()
                            if not line_str_t:
                                continue
                            
                            text_chunk_t = ""
                            if provider == "ollama":
                                try:
                                    data_json_t = json.loads(line_str_t)
                                    text_chunk_t = data_json_t.get('response', '')
                                except Exception:
                                    pass
                            else:
                                if line_str_t.startswith("data:"):
                                    data_str_t = line_str_t[len("data:"):].strip()
                                    if data_str_t == "[DONE]":
                                        break
                                    try:
                                        data_json_t = json.loads(data_str_t)
                                        if "choices" in data_json_t:
                                            text_chunk_t = data_json_t["choices"][0].get("delta", {}).get("content", "")
                                        elif data_json_t.get("type") == "content_block_delta":
                                            text_chunk_t = data_json_t.get("delta", {}).get("text", "")
                                    except Exception:
                                        pass
                                        
                            if text_chunk_t:
                                self.wfile.write(text_chunk_t.encode('utf-8'))
                                self.wfile.flush()
                                sys.stdout.write(text_chunk_t)
                                sys.stdout.flush()
                                thinker_raw += text_chunk_t
                                
                    if buffer_t:
                        line_str_t = buffer_t.decode('utf-8').strip()
                        if line_str_t:
                            text_chunk_t = ""
                            if provider == "ollama":
                                try:
                                    data_json_t = json.loads(line_str_t)
                                    text_chunk_t = data_json_t.get('response', '')
                                except Exception:
                                    pass
                            else:
                                if line_str_t.startswith("data:"):
                                    data_str_t = line_str_t[len("data:"):].strip()
                                    try:
                                        data_json_t = json.loads(data_str_t)
                                        if "choices" in data_json_t:
                                            text_chunk_t = data_json_t["choices"][0].get("delta", {}).get("content", "")
                                    except Exception:
                                        pass
                            if text_chunk_t:
                                self.wfile.write(text_chunk_t.encode('utf-8'))
                                self.wfile.flush()
                                sys.stdout.write(text_chunk_t)
                                sys.stdout.flush()
                                thinker_raw += text_chunk_t
                                
                print("\n[Thinker Stream finished] Extracting plan...")
                thinker_plan = extract_json_from_text(thinker_raw)
            except Exception as te:
                print(f"[Thinker Error] Fallback to direct: {te}")
                thinker_plan = {
                    "project_name": "Direct Generation",
                    "description": "Generating application from prompt",
                    "clarifying_questions": []
                }
            
            if not thinker_plan:
                thinker_plan = {
                    "project_name": "Direct Generation",
                    "description": "Generating application from prompt",
                    "clarifying_questions": []
                }
                
            clarifying_questions = thinker_plan.get('clarifying_questions', [])
            if clarifying_questions and isinstance(clarifying_questions, list):
                # Save state and stream questions
                try:
                    with open(state_path, 'w', encoding='utf-8') as f:
                        json.dump({
                            "original_prompt": prompt,
                            "thinker_plan": thinker_plan,
                            "pending_questions": True,
                            "graph": current_graph
                        }, f, indent=4)
                except Exception:
                    pass
                
                question_text = "\n\n[QUESTION] Please answer the following clarifying question(s):\n\n"
                for i, q in enumerate(clarifying_questions, 1):
                    question_text += f"{i}. {q}\n"
                
                # Save thinker questions to history
                chat_history.append({"role": "user", "content": prompt})
                chat_history.append({"role": "assistant", "content": question_text.strip()})
                try:
                    with open(history_path, 'w', encoding='utf-8') as hf:
                        json.dump(chat_history, hf, indent=4)
                except Exception:
                    pass

                self.wfile.write(question_text.encode('utf-8'))
                self.wfile.flush()
                return
            else:
                # Delete state if no questions
                if os.path.exists(state_path):
                    try:
                        os.remove(state_path)
                    except Exception:
                        pass
                # Stream transitioning to Coder
                self.wfile.write("\n\n⚡ Generating visual node graph...\n\n".encode('utf-8'))
                self.wfile.flush()
        
        # --- Coder Phase ---
        if is_answer:
            coder_user_prompt = f"""Original User Request: {original_prompt}
Architect Plan: {json.dumps(thinker_plan, indent=2)}
Clarifying Questions: {json.dumps(clarifying_questions, indent=2)}
User Answers: {prompt}
 
Current Graph Structure:
{json.dumps(current_graph, indent=2)}
"""
        else:
            coder_user_prompt = f"""User Request: {prompt}
Architect Plan: {json.dumps(thinker_plan, indent=2)}
 
Current Graph Structure:
{json.dumps(current_graph, indent=2)}
"""
            
        coder_system_prompt = get_coder_system_prompt()
        url, headers, data = get_provider_request_details(provider, ai_config, api_key, coder_system_prompt, coder_user_prompt, stream=True, chat_history=chat_history)
        
        try:
            req = urllib.request.Request(
                url,
                data=json.dumps(data).encode('utf-8'),
                headers=headers
            )
            with urllib.request.urlopen(req, timeout=600) as response:
                buffer = b""
                full_coder_text = ""
                
                def process_line(line_str):
                    nonlocal full_coder_text
                    if not line_str:
                        return True
                    
                    text_chunk = ""
                    if provider == "ollama":
                        try:
                            data_json = json.loads(line_str)
                            text_chunk = data_json.get('response', '')
                        except Exception:
                            pass
                    else:
                        # SSE format parser
                        if line_str.startswith("data:"):
                            data_str = line_str[len("data:"):].strip()
                            if data_str == "[DONE]":
                                return False
                            try:
                                data_json = json.loads(data_str)
                                if "choices" in data_json:
                                    text_chunk = data_json["choices"][0].get("delta", {}).get("content", "")
                                elif data_json.get("type") == "content_block_delta":
                                    text_chunk = data_json.get("delta", {}).get("text", "")
                            except Exception:
                                pass
                                
                    if text_chunk:
                        # Print to Python console for visibility
                        sys.stdout.write(text_chunk)
                        sys.stdout.flush()
                        
                        self.wfile.write(text_chunk.encode('utf-8'))
                        self.wfile.flush()
                        full_coder_text += text_chunk
                    return True

                while True:
                    chunk = response.read(1024)
                    if not chunk:
                        break
                    buffer += chunk
                    while b"\n" in buffer:
                        line_bytes, buffer = buffer.split(b"\n", 1)
                        line = line_bytes.decode('utf-8').strip()
                        if not process_line(line):
                            break

                # Process any leftovers in buffer
                if buffer:
                    line = buffer.decode('utf-8').strip()
                    process_line(line)
                    
                print("\n[Stream finished] Extracting graph...")

                # Cleanup session state file if successful
                if os.path.exists(state_path):
                    try:
                        os.remove(state_path)
                    except Exception:
                        pass
                        
                # Extract and write the final compiled graph
                final_graph = extract_json_from_text(full_coder_text)
                if final_graph and isinstance(final_graph, dict) and "nodes" in final_graph:
                    # Normalize connection keys from 'from/to' to 'source/target'
                    connections = final_graph.get("connections", [])
                    if isinstance(connections, list):
                        normalized_conns = []
                        for conn in connections:
                            if isinstance(conn, dict):
                                source = conn.get("source") or conn.get("from")
                                target = conn.get("target") or conn.get("to")
                                if source and target:
                                    normalized_conns.append({
                                        "source": source,
                                        "target": target
                                    })
                        final_graph["connections"] = normalized_conns

                    graph_json_path = os.path.join(FRAMEWORK_DIR, 'node_editor', 'graph.json')
                    with open(graph_json_path, 'w', encoding='utf-8') as f:
                        json.dump(final_graph, f, indent=4)
                        print(f"✅ Successfully wrote generated graph to: {graph_json_path}")
                    
                    # Append coder response to history and save
                    chat_history.append({"role": "user", "content": prompt})
                    chat_history.append({"role": "assistant", "content": clean_history_text(full_coder_text)})
                    try:
                        with open(history_path, 'w', encoding='utf-8') as hf:
                            json.dump(chat_history, hf, indent=4)
                    except Exception:
                        pass
                else:
                    print("⚠️ Coder text did not contain valid graph JSON or was empty.")
                    print("Raw Coder Response content starts with:")
                    print(full_coder_text[:500] if full_coder_text else "EMPTY RESPONSE")
                        
        except urllib.error.HTTPError as he:
            self.send_response(he.code)
            self.send_header('Content-Type', 'text/plain; charset=utf-8')
            self.end_headers()
            try:
                error_body = he.read().decode('utf-8')
                self.wfile.write(f"API Error ({he.code}): {error_body}".encode('utf-8'))
            except Exception:
                self.wfile.write(f"HTTP Error ({he.code}): {he.reason}".encode('utf-8'))
        except Exception as e:
            self.send_response(500)
            self.send_header('Content-Type', 'text/plain; charset=utf-8')
            self.end_headers()
            self.wfile.write(f"Connection error: {str(e)}".encode('utf-8'))

    def handle_deploy(self):
        global active_process
        content_length = int(self.headers['Content-Length'])
        post_data = self.rfile.read(content_length)
        graph_data = json.loads(post_data.decode('utf-8'))

        # 1. Write the graph locally to node_editor/graph.json
        graph_json_path = os.path.join(FRAMEWORK_DIR, 'node_editor', 'graph.json')
        with open(graph_json_path, 'w', encoding='utf-8') as f:
            json.dump(graph_data, f, indent=4)

        # 2. Try hitting port 8080 deploy API (Preferred method)
        try:
            req = urllib.request.Request(
                "http://localhost:8080/api/deploy",
                data=json.dumps(graph_data).encode('utf-8'),
                headers={"Content-Type": "application/json"}
            )
            with urllib.request.urlopen(req, timeout=10) as res:
                response_data = json.loads(res.read().decode('utf-8'))
                self.send_response(200)
                self.send_header('Content-Type', 'application/json')
                self.end_headers()
                self.wfile.write(json.dumps(response_data).encode())
                return
        except Exception as e:
            # If port 8080 is not running, compile and run locally as fallback
            pass

        # 3. Local Compile Fallback
        try:
            # Import and compile
            sys.path.insert(0, FRAMEWORK_DIR)
            from node_editor.node_backend import EditorHandler
            handler = EditorHandler.__new__(EditorHandler)
            handler.compile_graph(graph_data)

            # Terminate active process on port 8000 if running
            if active_process:
                active_process.terminate()
                active_process.wait()
                active_process = None

            # Force kill port holding 8000
            port = 8000
            for n in graph_data.get('nodes', []):
                if n['type'] == 'ServerNode':
                    port = int(n.get('config', {}).get('port', 8000))
                    break
            
            try:
                kill_cmd = f"Get-NetTCPConnection -LocalPort {port} -ErrorAction SilentlyContinue | Select-Object -ExpandProperty OwningProcess | ForEach-Object {{ Stop-Process -Id $_ -Force }}"
                subprocess.run(["powershell", "-Command", kill_cmd], capture_output=True)
            except Exception:
                pass

            # Launch main.py
            main_py_path = os.path.join(FRAMEWORK_DIR, 'main.py')
            active_process = subprocess.Popen([sys.executable, main_py_path], cwd=FRAMEWORK_DIR)

            self.send_response(200)
            self.send_header('Content-Type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({"status": "success", "message": "Compiled locally successfully!"}).encode())

        except Exception as compile_err:
            self.send_response(500)
            self.send_header('Content-Type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({"status": "error", "message": str(compile_err)}).encode())

if __name__ == '__main__':
    from http.server import HTTPServer
    from socketserver import ThreadingMixIn
    class ThreadedHTTPServer(ThreadingMixIn, HTTPServer): pass

    print(f"⚡ AI Workspace Builder starting on http://localhost:{PORT}")
    threading.Timer(0.5, lambda: webbrowser.open(f"http://localhost:{PORT}")).start()

    with ThreadedHTTPServer(("", PORT), AIEditorHandler) as httpd:
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nShutting down AI Workspace Builder...")
