# AUTO-GENERATED BY NODE EDITOR COMPILER
import socketserver
from nodes.server_node import ServerNode
from nodes.http_requests_node import HTTPRequestsNode
from nodes.url_node import URLNode
from nodes.template_node import RenderNode
from nodes.logic_node import LogicNode
from nodes.route_node import RouterNode
from nodes.context_node import ContextNode
from plugins.logger import ActionLoggerNode
from plugins.security import AntiBotNode
from plugins.security import RateLimitNode
from plugins.security import CSRFNode
from nodes.response import Response

# Initialize Database if needed

# Nodes Instantiation
servernode_node_42f0f91d = ServerNode(host='127.0.0.1', port=8000)
httprequestsnode_node_463dc491 = HTTPRequestsNode()
actionloggernode_node_630a0f20 = ActionLoggerNode()
ratelimitnode_node_4899a088 = RateLimitNode()
antibotnode_node_789fa014 = AntiBotNode()
csrfnode_node_5a10accc = CSRFNode()
urlnode_node_ea5e3b4a = URLNode('/')
urlnode_node_aa37ab65 = URLNode('/shop')
urlnode_node_f928646e = URLNode('/product/<id>')
urlnode_node_b1bb4012 = URLNode('/cart')
urlnode_node_baa46610 = URLNode('/cart/add')
urlnode_node_50dd4297 = URLNode('/cart/add_from_shop')
urlnode_node_172c8a35 = URLNode('/cart/remove')
urlnode_node_bdd5e5ef = URLNode('/checkout')
urlnode_node_37cf26cc = URLNode('/checkout/place')
urlnode_node_a89ed2e0 = URLNode('/order/success')
urlnode_node_66d287f6 = URLNode('/api/cart/add')
urlnode_node_acff5eda = URLNode('/api/cart-count')
urlnode_node_fb230ff9 = URLNode('/test-py')
urlnode_node_297859fd = URLNode('/demo-frontend')
urlnode_node_297861 = URLNode('/about')

from static.helpers import db, get_session_id, compute_cart_totals
def home_logic(req):
    category    = req.query_params.get('cat', '')
    session_id  = get_session_id(req)
    if category:
        products = db.fetchall(
            "SELECT * FROM products WHERE category=? ORDER BY id",
            (category,)
        )
    else:
        products = db.fetchall("SELECT * FROM products ORDER BY id")
    product_count = db.fetchall("SELECT COUNT(*) as cnt FROM products")[0]['cnt']
    cart_count_row = db.fetchall(
        "SELECT COALESCE(SUM(quantity),0) as cnt FROM cart WHERE session_id=?",
        (session_id,)
    )
    return {
        'products':         products,
        'product_count':    product_count,
        'current_category': category,
        'cart_count':       cart_count_row[0]['cnt'],
        'csrf_token':       req.context.get('csrf_token', ''),
    }

logicnode_node_a2378860 = LogicNode(home_logic)

from static.helpers import db, get_session_id, compute_cart_totals
def product_detail_logic(req):
    pid        = req.get_param('id') or req.url_params.get('id', 0)
    session_id = get_session_id(req)
    rows       = db.fetchall("SELECT * FROM products WHERE id=?", (int(pid),))
    if not rows:
        return {'product_name': 'Not Found', 'product_id': 0, 'product_price': '0',
                'product_description': '', 'product_image': '', 'product_category': '',
                'cart_count': 0, 'csrf_token': ''}
    p = rows[0]
    cart_count_row = db.fetchall(
        "SELECT COALESCE(SUM(quantity),0) as cnt FROM cart WHERE session_id=?",
        (session_id,)
    )
    return {
        'product_id':          p['id'],
        'product_name':        p['name'],
        'product_price':       f"{p['price']:.2f}",
        'product_description': p['description'],
        'product_image':       p['image_url'],
        'product_category':    p['category'],
        'cart_count':          cart_count_row[0]['cnt'],
        'csrf_token':          req.context.get('csrf_token', ''),
    }

logicnode_node_ada28e0d = LogicNode(product_detail_logic)

from static.helpers import db, get_session_id, compute_cart_totals
def cart_logic(req):
    session_id = get_session_id(req)
    cart_items = db.fetchall("""
        SELECT c.id as cart_id, c.quantity, p.name, p.price, p.image_url, p.category
        FROM cart c JOIN products p ON c.product_id = p.id
        WHERE c.session_id = ?
        ORDER BY c.id
    """, (session_id,))
    totals = compute_cart_totals(cart_items)
    flash_success = req.query_params.get('added', '')
    flash_name = req.query_params.get('name', '')
    totals.update({
        'cart_items':    cart_items,
        'cart_count':    totals['item_count'],
        'csrf_token':    req.context.get('csrf_token', ''),
        'flash_success': f"'{flash_name}' added to cart!" if flash_success else '',
        'flash_error':   '',
    })
    return totals

logicnode_node_e2a12a36 = LogicNode(cart_logic)

from static.helpers import db, get_session_id, compute_cart_totals
def cart_add_logic(req):
    session_id = get_session_id(req)
    product_id = req.get_param('product_id')
    quantity   = int(req.get_param('quantity') or 1)
    if not product_id:
        return Response.redirect('/cart')
    product_id = int(product_id)
    # Check if product exists
    rows = db.fetchall("SELECT * FROM products WHERE id=?", (product_id,))
    if not rows:
        return Response.redirect('/cart')
    product = rows[0]
    # Check if already in cart (same session)
    existing = db.fetchall(
        "SELECT id, quantity FROM cart WHERE session_id=? AND product_id=?",
        (session_id, product_id)
    )
    if existing:
        new_qty = existing[0]['quantity'] + quantity
        db.execute("UPDATE cart SET quantity=? WHERE id=?", (new_qty, existing[0]['id']))
    else:
        db.execute(
            "INSERT INTO cart (session_id, product_id, quantity) VALUES (?,?,?)",
            (session_id, product_id, quantity)
        )
    # Redirect back with flash message
    name_enc = urllib.parse.quote(product['name'])
    return Response.redirect(f'/cart?added=1&name={name_enc}')

logicnode_node_8e4cf37f = LogicNode(cart_add_logic)

from static.helpers import db, get_session_id, compute_cart_totals
def cart_add_from_shop_logic(req):
    session_id = get_session_id(req)
    product_id = req.get_param('product_id')
    quantity   = int(req.get_param('quantity') or 1)
    
    if not product_id:
        return Response.redirect('/shop')
        
    product_id = int(product_id)
    
    # Check if product exists
    rows = db.fetchall("SELECT * FROM products WHERE id=?", (product_id,))
    if not rows:
        return Response.redirect('/shop')
        
    # Check if already in cart
    existing = db.fetchall(
        "SELECT id, quantity FROM cart WHERE session_id=? AND product_id=?",
        (session_id, product_id)
    )
    
    redirect_url = req.get_param('redirect_url') or '/shop'
    
    if existing:
        new_qty = existing[0]['quantity'] + quantity
        db.execute("UPDATE cart SET quantity=? WHERE id=?", (new_qty, existing[0]['id']))
    else:
        db.execute(
            "INSERT INTO cart (session_id, product_id, quantity) VALUES (?,?,?)",
            (session_id, product_id, quantity)
        )
        
    # Redirect back locally
    return Response.redirect(redirect_url)

logicnode_node_ea26aefb = LogicNode(cart_add_from_shop_logic)

from static.helpers import db, get_session_id, compute_cart_totals
def cart_remove_logic(req):
    cart_id = req.get_param('cart_id')
    if cart_id:
        db.execute("DELETE FROM cart WHERE id=?", (int(cart_id),))
    return Response.redirect('/cart')

logicnode_node_38f5c7ca = LogicNode(cart_remove_logic)

from static.helpers import db, get_session_id, compute_cart_totals
def checkout_logic(req):
    session_id = get_session_id(req)
    cart_items = db.fetchall("""
        SELECT c.id as cart_id, c.quantity, p.name, p.price, p.image_url, p.category
        FROM cart c JOIN products p ON c.product_id = p.id
        WHERE c.session_id = ?
        ORDER BY c.id
    """, (session_id,))
    if not cart_items:
        return Response.redirect('/cart')
    totals = compute_cart_totals(cart_items)
    totals.update({
        'cart_items':  cart_items,
        'cart_count':  totals['item_count'],
        'csrf_token':  req.context.get('csrf_token', ''),
        'flash_error': req.query_params.get('error', ''),
    })
    return totals

logicnode_node_4215f0d1 = LogicNode(checkout_logic)

from static.helpers import db, get_session_id, compute_cart_totals
def checkout_place_logic(req):
    session_id = get_session_id(req)
    name       = req.get_param('name', '').strip()
    email      = req.get_param('email', '').strip()
    address    = req.get_param('address', '').strip()
    phone      = req.get_param('phone', '').strip()

    if not name or not email or not address:
        return Response.redirect('/checkout?error=Please+fill+all+required+fields')

    # Get cart items
    cart_items = db.fetchall("""
        SELECT c.id as cart_id, c.quantity, p.id as product_id, p.name, p.price
        FROM cart c JOIN products p ON c.product_id = p.id
        WHERE c.session_id = ?
    """, (session_id,))

    if not cart_items:
        return Response.redirect('/cart?error=Cart+is+empty')

    totals = compute_cart_totals(cart_items)
    total  = totals['total_raw']

    # Insert order
    db.execute(
        "INSERT INTO orders (session_id, name, email, address, phone, total) VALUES (?,?,?,?,?,?)",
        (session_id, name, email, address, phone, total)
    )
    # Get the order id
    order_row = db.fetchall("SELECT id FROM orders WHERE session_id=? ORDER BY id DESC LIMIT 1", (session_id,))
    order_id  = order_row[0]['id'] if order_row else '??'

    # Insert order items
    items_data = [(order_id, item['product_id'], item['quantity'], item['price']) for item in cart_items]
    db.executemany(
        "INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (?,?,?,?)",
        items_data
    )

    # Clear the cart
    db.execute("DELETE FROM cart WHERE session_id=?", (session_id,))

    # Store order info in context for redirect
    name_enc    = urllib.parse.quote(name)
    email_enc   = urllib.parse.quote(email)
    addr_enc    = urllib.parse.quote(address)
    total_enc   = urllib.parse.quote(f"{total:.2f}")
    return Response.redirect(
        f'/order/success?order_id={order_id}&name={name_enc}'
        f'&email={email_enc}&address={addr_enc}&total={total_enc}'
    )

logicnode_node_699b71b9 = LogicNode(checkout_place_logic)

from static.helpers import db, get_session_id, compute_cart_totals
def order_success_logic(req):
    session_id = get_session_id(req)
    order_id   = req.query_params.get('order_id', '???')
    name       = req.query_params.get('name', 'Customer')
    email      = req.query_params.get('email', '')
    address    = req.query_params.get('address', '')
    total      = req.query_params.get('total', '0.00')
    return {
        'order_id':         order_id,
        'customer_name':    name,
        'customer_email':   email,
        'customer_address': address,
        'order_total':      total,
        'cart_count':       0,
        'csrf_token':       req.context.get('csrf_token', ''),
    }

logicnode_node_f193a041 = LogicNode(order_success_logic)

from static.helpers import db, get_session_id, compute_cart_totals
def api_cart_add_logic(req):
    session_id = get_session_id(req)
    product_id = req.get_param('product_id')
    quantity   = int(req.get_param('quantity') or 1)
    if not product_id:
        return json.dumps({'error': 'No product_id'})
    product_id = int(product_id)
    rows = db.fetchall("SELECT * FROM products WHERE id=?", (product_id,))
    if not rows:
        return json.dumps({'error': 'Product not found'})
    existing = db.fetchall(
        "SELECT id, quantity FROM cart WHERE session_id=? AND product_id=?",
        (session_id, product_id)
    )
    if existing:
        new_qty = existing[0]['quantity'] + quantity
        db.execute("UPDATE cart SET quantity=? WHERE id=?", (new_qty, existing[0]['id']))
    else:
        db.execute(
            "INSERT INTO cart (session_id, product_id, quantity) VALUES (?,?,?)",
            (session_id, product_id, quantity)
        )
    cart_count = db.fetchall(
        "SELECT COALESCE(SUM(quantity),0) as cnt FROM cart WHERE session_id=?",
        (session_id,)
    )[0]['cnt']
    return Response.json({'cart_count': cart_count, 'status': 'added'})

logicnode_node_32a2c2e6 = LogicNode(api_cart_add_logic)

from static.helpers import db, get_session_id, compute_cart_totals
def api_cart_count_logic(req):
    session_id = get_session_id(req)
    cnt = db.fetchall(
        "SELECT COALESCE(SUM(quantity),0) as cnt FROM cart WHERE session_id=?",
        (session_id,)
    )[0]['cnt']
    return Response.json({'count': cnt})

logicnode_node_9b18f0c1 = LogicNode(api_cart_count_logic)
rendernode_node_a5fac370 = RenderNode('test_pyscript.html')
rendernode_node_b29ad28e = RenderNode('demo_frontend.html')

def node_logic(request):
    import time
    from datetime import datetime
    from nodes.response import StreamingResponse

    def live_clock():
        # Ye loop lagatar chalta rahega jab tak user page open rakhega
        while True:
            # Current time nikal kar format karein (Hours:Minutes:Seconds)
            current_time = datetime.now().strftime("%H:%M:%S")
            
            # HTML span bhej kar time dikhayein
            yield f"<span style='font-family: monospace; font-size: 2rem; color: #10b981; font-weight: bold;'>{current_time}</span>"
            
            # Har naya time bhejne ke baad 1 second hold karein
            time.sleep(1)
            
    # 'result' key mein stream ko bhej dein taaki template {{ result | safe }} usko catch karle
    return {"result": StreamingResponse(live_clock())}

            
  

contextnode_node_297865 = ContextNode(node_logic)
rendernode_node_5b707f69 = RenderNode('shop.html')
rendernode_node_4439bbdd = RenderNode('product.html')
rendernode_node_47db0e8b = RenderNode('cart.html')
rendernode_node_b5e3eb77 = RenderNode('checkout.html')
rendernode_node_ee0994d4 = RenderNode('order_success.html')
rendernode_node_297862 = RenderNode('About.html')

# Node Connection Chain
servernode_node_42f0f91d.connect(httprequestsnode_node_463dc491)
httprequestsnode_node_463dc491.connect(actionloggernode_node_630a0f20)
actionloggernode_node_630a0f20.connect(ratelimitnode_node_4899a088)
ratelimitnode_node_4899a088.connect(antibotnode_node_789fa014)
antibotnode_node_789fa014.connect(csrfnode_node_5a10accc)
router_node_auto_1 = RouterNode([urlnode_node_ea5e3b4a, urlnode_node_aa37ab65, urlnode_node_f928646e, urlnode_node_b1bb4012, urlnode_node_baa46610, urlnode_node_50dd4297, urlnode_node_172c8a35, urlnode_node_bdd5e5ef, urlnode_node_37cf26cc, urlnode_node_a89ed2e0, urlnode_node_66d287f6, urlnode_node_acff5eda, urlnode_node_fb230ff9, urlnode_node_297859fd, urlnode_node_297861])
csrfnode_node_5a10accc.connect(router_node_auto_1)
urlnode_node_ea5e3b4a.connect(logicnode_node_a2378860)
urlnode_node_aa37ab65.connect(logicnode_node_a2378860)
urlnode_node_f928646e.connect(logicnode_node_ada28e0d)
urlnode_node_b1bb4012.connect(logicnode_node_e2a12a36)
urlnode_node_baa46610.connect(logicnode_node_8e4cf37f)
urlnode_node_50dd4297.connect(logicnode_node_ea26aefb)
urlnode_node_172c8a35.connect(logicnode_node_38f5c7ca)
urlnode_node_bdd5e5ef.connect(logicnode_node_4215f0d1)
urlnode_node_37cf26cc.connect(logicnode_node_699b71b9)
urlnode_node_a89ed2e0.connect(logicnode_node_f193a041)
urlnode_node_66d287f6.connect(logicnode_node_32a2c2e6)
urlnode_node_acff5eda.connect(logicnode_node_9b18f0c1)
urlnode_node_fb230ff9.connect(rendernode_node_a5fac370)
urlnode_node_297859fd.connect(rendernode_node_b29ad28e)
urlnode_node_297861.connect(contextnode_node_297865)
logicnode_node_a2378860.connect(rendernode_node_5b707f69)
logicnode_node_ada28e0d.connect(rendernode_node_4439bbdd)
logicnode_node_e2a12a36.connect(rendernode_node_47db0e8b)
logicnode_node_4215f0d1.connect(rendernode_node_b5e3eb77)
logicnode_node_f193a041.connect(rendernode_node_ee0994d4)
contextnode_node_297865.connect(rendernode_node_297862)

# Start Server
print('Node Editor Generated Server starting...')
print(f'  -> http://{servernode_node_42f0f91d.host}:{servernode_node_42f0f91d.port}')
from nodes.server_node import FrameworkHandler
FrameworkHandler.server_node = servernode_node_42f0f91d
FrameworkHandler._middleware_chain = None  # Reset cache on redeploy
from http.server import HTTPServer
from socketserver import ThreadingMixIn
class ThreadedHTTPServer(ThreadingMixIn, HTTPServer): pass
with ThreadedHTTPServer((servernode_node_42f0f91d.host, servernode_node_42f0f91d.port), FrameworkHandler) as httpd:
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        pass