"""
wsgi.py — Node Framework WSGI Adapter

WSGI = Web Server Gateway Interface
Isse framework Gunicorn, uWSGI, Apache, Nginx ke saath chal sakta hai.

Usage (Production):
    gunicorn wsgi:application --workers 4 --bind 0.0.0.0:8000

Usage (Dev, same as before):
    python main.py

How it works:
    WSGI standard ek function chahta hai: application(environ, start_response)
    Ye module main.py ka ServerNode graph lete hai aur us pe WSGI wrapper lagata hai.

Full deployment example (Windows/Linux):
    pip install gunicorn
    gunicorn wsgi:application --workers 4 --bind 0.0.0.0:8000 --reload
"""
import io
import sys
import os

# Add framework root to path
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
if BASE_DIR not in sys.path:
    sys.path.insert(0, BASE_DIR)

import settings


# ---------------------------------------------------------------------------
# WSGI Request Wrapper
# ---------------------------------------------------------------------------

class WSGIRequestWrapper:
    """
    Wraps a WSGI environ dict to look like our RequestWrapper.
    So all existing nodes work unchanged with WSGI servers.
    """
    import urllib.parse as _up
    import json as _json

    def __init__(self, environ):
        import urllib.parse
        self.environ    = environ
        self.method     = environ.get('REQUEST_METHOD', 'GET').upper()
        self.path       = environ.get('PATH_INFO', '/')
        self.headers    = WSGIHeaders(environ)
        self.url_params = {}
        self.context    = {}

        # Query string
        qs = environ.get('QUERY_STRING', '')
        self.query_params = {
            k: v[0] if len(v) == 1 else v
            for k, v in urllib.parse.parse_qs(qs).items()
        }

        # Body
        self.body_bytes = b''
        self.params     = {}
        self._files     = {}

        if self.method in ('POST', 'PUT', 'PATCH', 'DELETE'):
            try:
                length = int(environ.get('CONTENT_LENGTH', 0) or 0)
                if length > 0:
                    self.body_bytes = environ['wsgi.input'].read(length)
                    ct = environ.get('CONTENT_TYPE', '')
                    if 'application/x-www-form-urlencoded' in ct:
                        self.params = urllib.parse.parse_qs(
                            self.body_bytes.decode('utf-8', errors='replace')
                        )
            except Exception:
                pass

        # Fake handler for middleware/security nodes that do client_address
        self.handler = _FakeHandler(environ)

    @property
    def content_type(self):
        return self.environ.get('CONTENT_TYPE', '').lower()

    def get_param(self, key, default=None):
        if key in self.url_params:
            return self.url_params[key]
        v = self.params.get(key)
        return v[0] if v else default

    def get_json(self):
        import json
        try:
            return json.loads(self.body_bytes.decode('utf-8'))
        except Exception:
            return None

    def get_file(self, key):
        return self._files.get(key)


class WSGIHeaders:
    """Dict-like wrapper for WSGI environ HTTP headers."""
    def __init__(self, environ):
        self._env = environ

    def get(self, name, default=None):
        key = 'HTTP_' + name.upper().replace('-', '_')
        # Special cases
        if name.lower() == 'content-type':
            key = 'CONTENT_TYPE'
        elif name.lower() == 'content-length':
            key = 'CONTENT_LENGTH'
        return self._env.get(key, default)

    def __contains__(self, name):
        return self.get(name) is not None

    def __getitem__(self, name):
        v = self.get(name)
        if v is None:
            raise KeyError(name)
        return v


class _FakeHandler:
    """Mimics http.server handler for nodes that access handler.client_address."""
    def __init__(self, environ):
        addr = environ.get('REMOTE_ADDR', '127.0.0.1')
        self.client_address = (addr, 0)


# ---------------------------------------------------------------------------
# WSGI Application Factory
# ---------------------------------------------------------------------------

def _load_server_node():
    """
    Import main.py's server_node graph.
    main.py is auto-generated by the Node Editor.
    """
    import importlib.util
    main_path = os.path.join(BASE_DIR, 'main.py')
    spec = importlib.util.spec_from_file_location('main', main_path)
    mod  = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    # main.py sets FrameworkHandler.server_node — grab it
    from nodes.server_node import FrameworkHandler
    return FrameworkHandler.server_node


def create_app(server_node=None):
    """
    Create and return a WSGI-compatible application callable.

    Args:
        server_node : The root ServerNode. If None, loads from main.py.

    Returns:
        callable(environ, start_response) — standard WSGI app
    """
    from nodes.response import Response

    if server_node is None:
        server_node = _load_server_node()

    def application(environ, start_response):
        """WSGI entry point."""
        request = WSGIRequestWrapper(environ)

        # Run the node graph
        try:
            result = server_node.start_flow(request)
        except Exception as e:
            import traceback
            tb  = traceback.format_exc()
            print(f"[WSGI] Unhandled error: {e}\n{tb}")
            result = Response.server_error(str(e))

        # Normalize result to Response
        if result is None:
            # Check static file
            path = environ.get('PATH_INFO', '/')
            if path.startswith(settings.STATIC_URL):
                result = _serve_static(path)
            else:
                result = Response.not_found(f"No route matched: {path}")
        elif isinstance(result, str):
            result = Response(body=result)

        # Serialize
        body_bytes = result.to_bytes()
        headers = [
            ('Content-Type',   result.content_type),
            ('Content-Length', str(len(body_bytes))),
            ('X-Content-Type-Options', 'nosniff'),
            ('X-Frame-Options',        'SAMEORIGIN'),
        ]
        for k, v in result.headers.items():
            headers.append((k, v))

        start_response(f"{result.status} {_status_text(result.status)}", headers)
        return [body_bytes]

    return application


def _serve_static(path):
    """Serve a static file from settings.STATIC_ROOT."""
    from nodes.response import Response
    rel_path  = path[len(settings.STATIC_URL):]
    full_path = os.path.join(settings.STATIC_ROOT, rel_path)
    if not os.path.isfile(full_path):
        return Response.not_found(f"Static file not found: {rel_path}")
    ext_map = {
        '.css': 'text/css', '.js': 'application/javascript',
        '.png': 'image/png', '.jpg': 'image/jpeg', '.svg': 'image/svg+xml',
        '.ico': 'image/x-icon', '.woff2': 'font/woff2',
    }
    ext = os.path.splitext(full_path)[1].lower()
    ct  = ext_map.get(ext, 'application/octet-stream')
    with open(full_path, 'rb') as f:
        body = f.read()
    return Response(body=body, content_type=ct)


def _status_text(code):
    _CODES = {
        200: 'OK', 201: 'Created', 204: 'No Content',
        301: 'Moved Permanently', 302: 'Found',
        400: 'Bad Request', 401: 'Unauthorized', 403: 'Forbidden',
        404: 'Not Found', 405: 'Method Not Allowed', 429: 'Too Many Requests',
        500: 'Internal Server Error', 503: 'Service Unavailable',
    }
    return _CODES.get(code, 'Unknown')


# ---------------------------------------------------------------------------
# Module-level application (for Gunicorn: gunicorn wsgi:application)
# ---------------------------------------------------------------------------
# NOTE: Only auto-loads when running via Gunicorn or direct call.
#       Importing this module for testing does NOT start the server.
application = None

def _lazy_load():
    """Called by Gunicorn worker on first request if application is None."""
    global application
    if application is None:
        try:
            application = create_app()
        except Exception as _e:
            print(f"[WSGI] Warning: Could not load app: {_e}")
    return application

# Auto-load only when run directly (not on import)
if __name__ == '__wsgi__' or (
    '__name__' in dir() and
    os.environ.get('SERVER_SOFTWARE', '').startswith('gunicorn')
):
    _lazy_load()