// AUTO-GENERATED BY JS_NODE COMPILER
const Response = {
    json: (data, status = 200) => ({
        _is_response: true,
        body: JSON.stringify(data),
        status: status,
        content_type: 'application/json; charset=utf-8'
    }),
    redirect: (url, status = 302) => ({
        _is_response: true,
        body: `<html><body>Redirecting to <a href="${url}">${url}</a></body></html>`,
        status: status,
        content_type: 'text/html; charset=utf-8',
        headers: { 'Location': url }
    }),
    not_found: (message = '404 Not Found') => ({
        _is_response: true,
        body: message,
        status: 404,
        content_type: 'text/html; charset=utf-8'
    }),
    forbidden: (message = '403 Forbidden') => ({
        _is_response: true,
        body: message,
        status: 403,
        content_type: 'text/html; charset=utf-8'
    })
};

function process_logic(request) {
    // This is a Node.js backend function, so we cannot use DOM APIs like document, window, etc.
    // The provided frontend JavaScript code is not applicable here.
    // Instead, we simulate the initial state for a product cart system.

    const context = request.context || {};

    // Initialize basic cart and product data
    if (!context.cart) {
        context.cart = [];
    }

    if (!context.products) {
        context.products = [
            { id: 1, name: "Product 1", price: 29.99 },
            { id: 2, name: "Product 2", price: 39.99 },
            { id: 3, name: "Product 3", price: 49.99 }
        ];
    }

    // Simulate adding a product to cart
    if (request.input && request.input.add_to_cart) {
        const productId = request.input.add_to_cart;
        const product = context.products.find(p => p.id === productId);

        if (product) {
            context.cart.push({
                id: product.id,
                name: product.name,
                price: product.price,
                timestamp: new Date().toISOString()
            });
        }
    }

    // Return updated context
    return {
        context: context
    };
}

// Runner
const fs = require('fs');
try {
    const inputData = fs.readFileSync(0, 'utf-8');
    const payload = JSON.parse(inputData);
    
    // Find function to execute
    let execFunc = process_logic;
    if (typeof execFunc !== 'function') {
        throw new Error("No process_logic function found.");
    }
    const result = execFunc(payload);
    console.log(JSON.stringify({ status: "success", result: result || {} }));
} catch (e) {
    console.error(JSON.stringify({ status: "error", error: e.message, stack: e.stack }));
    process.exit(1);
}
